name: Demo CI

on: push
  branches:
    - master
  paths-ignore:
    - '**/README.md'
    - '**/LICENCE'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm test
      - run: docker build . -t greenict/demo-api
      - run: npm run lint
